### Get Chain
GET http://localhost:1010/chain

### Mine
GET http://localhost:1010/mine?user=benjaminellmer

### Create transaction
POST http://localhost:1010/transaction
Content-Type: application/json

{
  "sender": "benjaminellmer",
  "receiver": "benekaiser",
  "amount": 5
}

### Get Balance
GET http://localhost:1010/balance?user=benekaiser

### Get Balance
GET http://localhost:1010/balance?user=benjaminellmer

### Register
GET http://localhost:1010/nodes/register?nodeUrl=http://localhost:2020

### Resolve
GET http://localhost:1010/nodes/resolve

### Mine
GET http://localhost:2020/mine?user=benjaminellmer
